### ISSUE TITLE
Error "Updating indexes"

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#54]
I'm not 100% sure this comes from OEDT, but after updating to 9.0.0 and restarting Eclipse (several times, also with -clean) I get the following error:

![image](https://user-images.githubusercontent.com/8639525/55310619-376d9480-5461-11e9-98ba-8fe80fc395c3.png)

**Comment by lneumeier** [comment]
Can post the .log file %workspace%\.metadata\.log?

**Comment by LievenDeFoor** [comment]
[log.txt](https://github.com/omecra/de.omecra.oedt.updatesite/files/3028234/log.txt)

I had to rename it because GitHub refuses to upload hidden files...

**Comment by LievenDeFoor** [comment]
Now that I'm looking at the log file I think something is wrong in with the Maven Eclipse plugin...
But I do see other tooltip related OEDT errors as well...

**Comment by lneumeier** [comment]
```
!ENTRY org.eclipse.core.jobs 4 2 2019-04-01 09:29:52.383
!MESSAGE An internal error occurred during: "Updating indexes".
!STACK 0
java.lang.NoClassDefFoundError: org/eclipse/core/runtime/internal/adaptor/BasicLocation
	at org.eclipse.m2e.core.internal.index.nexus.EquinoxLocker.lock(EquinoxLocker.java:28)
	at org.eclipse.m2e.core.internal.index.nexus.NexusIndexManager.updateRemoteIndex(NexusIndexManager.java:1121)
	at org.eclipse.m2e.core.internal.index.nexus.NexusIndexManager.updateIndex(NexusIndexManager.java:1083)
	at org.eclipse.m2e.core.internal.index.nexus.NexusIndexManager$1.run(NexusIndexManager.java:660)
	at org.eclipse.m2e.core.internal.index.nexus.IndexUpdaterJob.run(IndexUpdaterJob.java:72)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.ClassNotFoundException: org.eclipse.core.runtime.internal.adaptor.BasicLocation cannot be found by org.eclipse.m2e.core_1.4.0.20130601-0317
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:484)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(Unknown Source)
```

**Comment by lneumeier** [comment]
For the OEDT error, do you get any "error message" or is your launch configuration not working?

**Comment by lneumeier** [comment]
I'm closing this issue - the OEDT error is tracked through #55 .

**Comment by LievenDeFoor** [comment]
> For the OEDT error, do you get any "error message" or is your launch configuration not working?

I''ll create a new issue for this.
