### ISSUE TITLE
Latest supported version of Eclipse?

### ISSUE THREAD

**Issue by LievenDeFoor** [omecra/de.omecra.oedt.updatesite#126]
Hi,

I'm adventurous and tried setting up OE 12.2.7 with the latest Eclipse 2021-12 (4.22).
Installing the OE and OEDT plugins went without any error, but accessing the OEDT preferences, or trying to open an existing project gives all sorts of OEDT related errors...
What is the latest version of Eclipse known to work with OEDT + OE12.2?
The official version shipping with OE12.2.7 is Eclipse 4.13.

Regards,
Lieven

**Comment by lneumeier** [comment]
This should be eclipse 4.16.

After that, I'm getting 
`Caused by: java.lang.NoClassDefFoundError: org/eclipse/swt/internal/win32/FILETIME``

FILETIME was removed in 4.17.
https://git.eclipse.org/r/c/platform/eclipse.platform.swt/+/157771/6
https://projects.eclipse.org/projects/eclipse/releases/4.17.0/bugs
